//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""d9dcbd12-ad72-489c-acdb-1679971236ee"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""3169cba2-f8ae-482b-b638-d046a9204c25"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""74f7792a-c6a7-4e95-8fa2-25eeda986f86"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""a08429e1-c96d-4bd5-968a-acf4dba315a2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""Button"",
                    ""id"": ""1cb28394-eb59-441a-9794-d2271700d35e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""f4e1b578-1952-4aac-a60d-8153bd0c280b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dodge"",
                    ""type"": ""Button"",
                    ""id"": ""d3c591dd-f927-47e8-a4d0-80c82e2175fb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gather"",
                    ""type"": ""Button"",
                    ""id"": ""cf86c631-2743-499f-afe6-3fcc37641e04"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Quick1"",
                    ""type"": ""Button"",
                    ""id"": ""4ba72c00-4cdb-434c-b395-d4700bddf95d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Quick2"",
                    ""type"": ""Button"",
                    ""id"": ""7ac356dc-c5d2-470f-ab98-0ee5b4cef57d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Quick3"",
                    ""type"": ""Button"",
                    ""id"": ""45d609e0-3c98-4b8a-b8b8-1572bd6947f7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Quick4"",
                    ""type"": ""Button"",
                    ""id"": ""1a959c1e-11f0-489b-aa28-d02754b6cd54"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Quick5"",
                    ""type"": ""Button"",
                    ""id"": ""6767ffd8-3569-4496-a7c4-45cb10bd7370"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Quick6"",
                    ""type"": ""Button"",
                    ""id"": ""c18ebbce-4dbc-48b7-b040-907b65f93dca"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QuickSwap"",
                    ""type"": ""Button"",
                    ""id"": ""93f39077-abde-45f4-a21c-58d155324ca6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Debug"",
                    ""type"": ""Button"",
                    ""id"": ""55fdbb06-1baf-40ec-beb0-81deefae4d4a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""8b39383d-7785-4593-8de3-c14e5bc9813b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ee95306b-960b-4956-b1f9-f4f6bd629c19"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""dd51a46a-65ab-4f77-be4f-a201e4103a1d"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""71dace24-91f0-4d6c-965a-acefd0c32f37"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1cfb3a54-0689-43a3-9a94-dd646db5af89"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""07008962-6a17-42a3-b9eb-bc3577a3c6d9"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9d4558bf-9b85-4254-9175-692d67fa0bcb"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3280f3bf-db48-4396-9255-76645a45aaa4"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f01b87fe-75bd-4141-9e3f-e7a1e4cc6d53"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b5e011fe-e960-409b-b825-ccc3fcefbb31"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dodge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""94f67460-5cc9-4539-a2a3-d0bf5d8d5216"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gather"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41df066b-5d58-43f9-b5fa-0506d99a55f2"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quick1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dd67b124-664d-4da1-800f-84332ca841ce"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quick2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c3fe2af-720f-46b6-aa30-095ccc8dbc06"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quick3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87344464-a56d-4953-bff8-d1b70e3a65d7"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quick4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab4ec100-e59a-42dc-a9be-7717e29f43e7"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quick5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""56f50590-dbcb-49eb-b49f-6cb0834ceafd"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quick6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4232a5c-3deb-4bb5-8d57-e76756d29043"",
                    ""path"": ""<Keyboard>/slash"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Debug"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c6c26522-8101-40ae-9743-59b48498f739"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QuickSwap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Aim = m_Player.FindAction("Aim", throwIfNotFound: true);
        m_Player_Attack = m_Player.FindAction("Attack", throwIfNotFound: true);
        m_Player_Dodge = m_Player.FindAction("Dodge", throwIfNotFound: true);
        m_Player_Gather = m_Player.FindAction("Gather", throwIfNotFound: true);
        m_Player_Quick1 = m_Player.FindAction("Quick1", throwIfNotFound: true);
        m_Player_Quick2 = m_Player.FindAction("Quick2", throwIfNotFound: true);
        m_Player_Quick3 = m_Player.FindAction("Quick3", throwIfNotFound: true);
        m_Player_Quick4 = m_Player.FindAction("Quick4", throwIfNotFound: true);
        m_Player_Quick5 = m_Player.FindAction("Quick5", throwIfNotFound: true);
        m_Player_Quick6 = m_Player.FindAction("Quick6", throwIfNotFound: true);
        m_Player_QuickSwap = m_Player.FindAction("QuickSwap", throwIfNotFound: true);
        m_Player_Debug = m_Player.FindAction("Debug", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Look;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Aim;
    private readonly InputAction m_Player_Attack;
    private readonly InputAction m_Player_Dodge;
    private readonly InputAction m_Player_Gather;
    private readonly InputAction m_Player_Quick1;
    private readonly InputAction m_Player_Quick2;
    private readonly InputAction m_Player_Quick3;
    private readonly InputAction m_Player_Quick4;
    private readonly InputAction m_Player_Quick5;
    private readonly InputAction m_Player_Quick6;
    private readonly InputAction m_Player_QuickSwap;
    private readonly InputAction m_Player_Debug;
    public struct PlayerActions
    {
        private @PlayerInput m_Wrapper;
        public PlayerActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @Look => m_Wrapper.m_Player_Look;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Aim => m_Wrapper.m_Player_Aim;
        public InputAction @Attack => m_Wrapper.m_Player_Attack;
        public InputAction @Dodge => m_Wrapper.m_Player_Dodge;
        public InputAction @Gather => m_Wrapper.m_Player_Gather;
        public InputAction @Quick1 => m_Wrapper.m_Player_Quick1;
        public InputAction @Quick2 => m_Wrapper.m_Player_Quick2;
        public InputAction @Quick3 => m_Wrapper.m_Player_Quick3;
        public InputAction @Quick4 => m_Wrapper.m_Player_Quick4;
        public InputAction @Quick5 => m_Wrapper.m_Player_Quick5;
        public InputAction @Quick6 => m_Wrapper.m_Player_Quick6;
        public InputAction @QuickSwap => m_Wrapper.m_Player_QuickSwap;
        public InputAction @Debug => m_Wrapper.m_Player_Debug;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Look.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLook;
                @Jump.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Aim.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAim;
                @Aim.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAim;
                @Aim.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAim;
                @Attack.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAttack;
                @Dodge.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDodge;
                @Dodge.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDodge;
                @Dodge.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDodge;
                @Gather.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGather;
                @Gather.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGather;
                @Gather.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGather;
                @Quick1.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnQuick1;
                @Quick1.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnQuick1;
                @Quick1.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnQuick1;
                @Quick2.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnQuick2;
                @Quick2.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnQuick2;
                @Quick2.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnQuick2;
                @Quick3.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnQuick3;
                @Quick3.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnQuick3;
                @Quick3.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnQuick3;
                @Quick4.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnQuick4;
                @Quick4.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnQuick4;
                @Quick4.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnQuick4;
                @Quick5.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnQuick5;
                @Quick5.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnQuick5;
                @Quick5.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnQuick5;
                @Quick6.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnQuick6;
                @Quick6.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnQuick6;
                @Quick6.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnQuick6;
                @QuickSwap.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnQuickSwap;
                @QuickSwap.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnQuickSwap;
                @QuickSwap.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnQuickSwap;
                @Debug.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDebug;
                @Debug.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDebug;
                @Debug.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnDebug;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Aim.started += instance.OnAim;
                @Aim.performed += instance.OnAim;
                @Aim.canceled += instance.OnAim;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
                @Dodge.started += instance.OnDodge;
                @Dodge.performed += instance.OnDodge;
                @Dodge.canceled += instance.OnDodge;
                @Gather.started += instance.OnGather;
                @Gather.performed += instance.OnGather;
                @Gather.canceled += instance.OnGather;
                @Quick1.started += instance.OnQuick1;
                @Quick1.performed += instance.OnQuick1;
                @Quick1.canceled += instance.OnQuick1;
                @Quick2.started += instance.OnQuick2;
                @Quick2.performed += instance.OnQuick2;
                @Quick2.canceled += instance.OnQuick2;
                @Quick3.started += instance.OnQuick3;
                @Quick3.performed += instance.OnQuick3;
                @Quick3.canceled += instance.OnQuick3;
                @Quick4.started += instance.OnQuick4;
                @Quick4.performed += instance.OnQuick4;
                @Quick4.canceled += instance.OnQuick4;
                @Quick5.started += instance.OnQuick5;
                @Quick5.performed += instance.OnQuick5;
                @Quick5.canceled += instance.OnQuick5;
                @Quick6.started += instance.OnQuick6;
                @Quick6.performed += instance.OnQuick6;
                @Quick6.canceled += instance.OnQuick6;
                @QuickSwap.started += instance.OnQuickSwap;
                @QuickSwap.performed += instance.OnQuickSwap;
                @QuickSwap.canceled += instance.OnQuickSwap;
                @Debug.started += instance.OnDebug;
                @Debug.performed += instance.OnDebug;
                @Debug.canceled += instance.OnDebug;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnAim(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnDodge(InputAction.CallbackContext context);
        void OnGather(InputAction.CallbackContext context);
        void OnQuick1(InputAction.CallbackContext context);
        void OnQuick2(InputAction.CallbackContext context);
        void OnQuick3(InputAction.CallbackContext context);
        void OnQuick4(InputAction.CallbackContext context);
        void OnQuick5(InputAction.CallbackContext context);
        void OnQuick6(InputAction.CallbackContext context);
        void OnQuickSwap(InputAction.CallbackContext context);
        void OnDebug(InputAction.CallbackContext context);
    }
}
